import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import {Theme, ThemePanel} from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "DatoCMS x Hotspring Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Theme accentColor="red" radius="none" appearance="dark">
        {children}
          {/*<ThemePanel />*/}
      </Theme>
      </body>
    </html>
  );
}
